spring:
  thymeleaf:
    check-template: true
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:templates/
    check-template-location: true