spring:
  thymeleaf:
    check-template: true
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/WEB-INF/templates/
    check-template-location: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console